# Generated by Django 5.2.6 on 2025-11-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('services', models.JSONField(default=list)),
                ('date', models.DateField()),
                ('timeslot', models.CharField(max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'timeslot', 'name'],
                'indexes': [models.Index(fields=['date'], name='website_app_date_965bb0_idx'), models.Index(fields=['name'], name='website_app_name_7177d6_idx')],
            },
        ),
    ]
