# Generated by Django 6.0 on 2026-02-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_patient_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
