# Generated by Django 5.2.6 on 2026-02-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_patient_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
