# Generated by Django 5.2.6 on 2026-02-12 16:37

from django.db import migrations
from datetime import datetime

def forwards(apps, schema_editor):
    Appointment = apps.get_model("website", "Appointment")

    for appt in Appointment.objects.all():
        if appt.start_time is not None:
            continue
        ts = (appt.timeslot or "").strip()
        if not ts:
            continue

        try:
            t = datetime.strptime(ts, "%I:%M %p").time()
            appt.start_time = t
            appt.save(update_fields=["start_time"])
        except ValueError:
            continue

def backwards(apps, schema_editor):
    Appointment = apps.get_model("website", "Appointment")
    Appointment.objects.update(start_time=None)

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_appointment_start_time'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
