# Generated by Django 6.0 on 2026-02-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['name'], name='website_pat_name_d318b7_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone'], name='website_pat_phone_6e57b7_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['email'], name='website_pat_email_148a3f_idx'),
        ),
    ]
