# Generated by Django 6.0 on 2026-03-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_patient_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=16, null=True, unique=True),
        ),
    ]
