# Generated by Django 6.0 on 2026-04-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Perez Jr. Dental Clinic', max_length=140)),
                ('hero_subtitle', models.TextField(blank=True, default='Comfortable, modern dental care for every smile.')),
                ('hero_cta_text', models.CharField(default='Book an Appointment', max_length=80)),
                ('about_summary', models.TextField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('clinic_address', models.TextField(blank=True)),
                ('clinic_hours', models.TextField(blank=True)),
                ('service_1_title', models.CharField(blank=True, max_length=120)),
                ('service_1_summary', models.TextField(blank=True)),
                ('service_2_title', models.CharField(blank=True, max_length=120)),
                ('service_2_summary', models.TextField(blank=True)),
                ('service_3_title', models.CharField(blank=True, max_length=120)),
                ('service_3_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
            },
        ),
    ]
