# Generated by Django 6.0 on 2026-04-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontent',
            name='clinic_hours',
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hours_line_1_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hours_line_1_value',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hours_line_2_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hours_line_2_value',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Say goodbye to anxiety. We focus on gentle, compassionate care tailored to your comfort level, making every step—from cleaning to advanced procedure—as easy as possible.'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='hero_title',
            field=models.CharField(default="We're Here for You. <span>Dentistry That Understands.</span>", max_length=140),
        ),
    ]
