# Generated by Django 6.0 on 2026-04-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_remove_sitecontent_clinic_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='doctor_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='doctor_title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
