# Generated by Django 6.0 on 2026-04-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_sitecontent_doctor_bio_sitecontent_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='service_4_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='service_4_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='service_5_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='service_5_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='service_6_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='service_6_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='service_7_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='service_7_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='service_8_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='service_8_title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
