# Generated by Django 6.0 on 2026-04-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_sitecontent_service_4_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='about_heading',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_kicker',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
