# Generated by Django 6.0 on 2026-04-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_sitecontent_about_heading_sitecontent_about_kicker'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='home_doctor_heading',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='home_doctor_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='home_doctor_kicker',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='home_services_heading',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='home_services_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='home_services_kicker',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
