# Generated by Django 6.0 on 2026-04-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_sitecontent_home_doctor_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='hero_slide_2_cta_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hero_slide_2_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hero_slide_2_title',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
