# Generated by Django 6.0 on 2026-04-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_sitecontent_hero_slide_2_cta_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='home_intro_heading',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='home_intro_text',
            field=models.TextField(blank=True),
        ),
    ]
