# Generated by Django 6.0 on 2026-04-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_sitecontent_home_intro_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='about_founder_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_founder_title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
