# Generated by Django 6.0 on 2026-04-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_sitecontent_about_founder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='about_founder_photo',
            field=models.ImageField(blank=True, null=True, upload_to='site/founders/'),
        ),
    ]
