# Generated by Django 6.0 on 2026-04-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_sitecontent_about_founder_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='service_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/services/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='service_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/services/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='service_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/services/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='service_4_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/services/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='service_5_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/services/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='service_6_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/services/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='service_7_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/services/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='service_8_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/services/'),
        ),
    ]
