# Generated by Django 6.0 on 2026-04-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_sitecontent_service_1_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='hero_slide_1_background',
            field=models.ImageField(blank=True, null=True, upload_to='site/heroes/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hero_slide_2_background',
            field=models.ImageField(blank=True, null=True, upload_to='site/heroes/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='home_intro_background',
            field=models.ImageField(blank=True, null=True, upload_to='site/home/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='page_banner_background',
            field=models.ImageField(blank=True, null=True, upload_to='site/banners/'),
        ),
    ]
