# Generated by Django 6.0 on 2026-04-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_sitecontent_hero_slide_1_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='about_side_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/about/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='clinic_website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='contact_form_heading',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='contact_page_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='services_page_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Say goodbye to anxiety. We focus on gentle, compassionate care tailored to your comfort level, making every step - from cleaning to advanced procedure - as easy as possible.'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='hero_title',
            field=models.CharField(default="We're Here for You. Dentistry That Understands.", max_length=140),
        ),
    ]
