# Generated by Django 6.0 on 2026-04-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_sitecontent_about_side_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='clinic_landmarks',
            field=models.TextField(blank=True),
        ),
    ]
