from django import forms

from apps.public.models import SiteContent


class SiteContentForm(forms.ModelForm):
    class Meta:
        model = SiteContent
        fields = [
            "hero_title",
            "hero_subtitle",
            "hero_cta_text",
            "hero_slide_1_background",
            "hero_slide_2_title",
            "hero_slide_2_subtitle",
            "hero_slide_2_cta_text",
            "hero_slide_2_background",
            "home_intro_heading",
            "home_intro_text",
            "home_intro_background",
            "home_services_kicker",
            "home_services_heading",
            "home_services_intro",
            "home_doctor_kicker",
            "home_doctor_heading",
            "home_doctor_intro",
            "about_kicker",
            "about_heading",
            "about_summary",
            "about_founder_name",
            "about_founder_title",
            "about_founder_photo",
            "page_banner_background",
            "contact_phone",
            "contact_email",
            "clinic_address",
            "hours_line_1_label",
            "hours_line_1_value",
            "hours_line_2_label",
            "hours_line_2_value",
            "service_1_title",
            "service_1_summary",
            "service_1_image",
            "service_2_title",
            "service_2_summary",
            "service_2_image",
            "service_3_title",
            "service_3_summary",
            "service_3_image",
            "service_4_title",
            "service_4_summary",
            "service_4_image",
            "service_5_title",
            "service_5_summary",
            "service_5_image",
            "service_6_title",
            "service_6_summary",
            "service_6_image",
            "service_7_title",
            "service_7_summary",
            "service_7_image",
            "service_8_title",
            "service_8_summary",
            "service_8_image",
            "doctor_name",
            "doctor_title",
            "doctor_bio",

        ]
        widgets = {
            "hero_title": forms.TextInput(attrs={"class": "form-control"}),
            "hero_subtitle": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
            "hero_cta_text": forms.TextInput(attrs={"class": "form-control"}),
            "hero_slide_1_background": forms.ClearableFileInput(attrs={"class": "form-control"}),
            "hero_slide_2_title": forms.TextInput(attrs={"class": "form-control"}),
            "hero_slide_2_subtitle": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
            "hero_slide_2_cta_text": forms.TextInput(attrs={"class": "form-control"}),
            "hero_slide_2_background": forms.ClearableFileInput(attrs={"class": "form-control"}),
            "home_intro_heading": forms.TextInput(attrs={"class": "form-control"}),
            "home_intro_text": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
            "home_intro_background": forms.ClearableFileInput(attrs={"class": "form-control"}),
            "home_services_kicker": forms.TextInput(attrs={"class": "form-control"}),
            "home_services_heading": forms.TextInput(attrs={"class": "form-control"}),
            "home_services_intro": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
            "home_doctor_kicker": forms.TextInput(attrs={"class": "form-control"}),
            "home_doctor_heading": forms.TextInput(attrs={"class": "form-control"}),
            "home_doctor_intro": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
            "about_kicker": forms.TextInput(attrs={"class": "form-control"}),
            "about_heading": forms.TextInput(attrs={"class": "form-control"}),
            "about_summary": forms.Textarea(attrs={"class": "form-control", "rows": 5}),
            "about_founder_name": forms.TextInput(attrs={"class": "form-control"}),
            "about_founder_title": forms.TextInput(attrs={"class": "form-control"}),
            "about_founder_photo": forms.ClearableFileInput(attrs={"class": "form-control"}),
            "page_banner_background": forms.ClearableFileInput(attrs={"class": "form-control"}),
            "contact_phone": forms.TextInput(attrs={"class": "form-control"}),
            "contact_email": forms.EmailInput(attrs={"class": "form-control"}),
            "clinic_address": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
            "hours_line_1_label": forms.TextInput(attrs={"class": "form-control"}),
            "hours_line_1_value": forms.TextInput(attrs={"class": "form-control"}),
            "hours_line_2_label": forms.TextInput(attrs={"class": "form-control"}),
            "hours_line_2_value": forms.TextInput(attrs={"class": "form-control"}),
            "service_1_title": forms.TextInput(attrs={"class": "form-control"}),
            "service_1_summary": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
            "service_1_image": forms.ClearableFileInput(attrs={"class": "form-control"}),
            "service_2_title": forms.TextInput(attrs={"class": "form-control"}),
            "service_2_summary": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
            "service_2_image": forms.ClearableFileInput(attrs={"class": "form-control"}),
            "service_3_title": forms.TextInput(attrs={"class": "form-control"}),
            "service_3_summary": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
            "service_3_image": forms.ClearableFileInput(attrs={"class": "form-control"}),
            "service_4_title": forms.TextInput(attrs={"class": "form-control"}),
            "service_4_summary": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
            "service_4_image": forms.ClearableFileInput(attrs={"class": "form-control"}),
            "service_5_title": forms.TextInput(attrs={"class": "form-control"}),
            "service_5_summary": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
            "service_5_image": forms.ClearableFileInput(attrs={"class": "form-control"}),
            "service_6_title": forms.TextInput(attrs={"class": "form-control"}),
            "service_6_summary": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
            "service_6_image": forms.ClearableFileInput(attrs={"class": "form-control"}),
            "service_7_title": forms.TextInput(attrs={"class": "form-control"}),
            "service_7_summary": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
            "service_7_image": forms.ClearableFileInput(attrs={"class": "form-control"}),
            "service_8_title": forms.TextInput(attrs={"class": "form-control"}),
            "service_8_summary": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
            "service_8_image": forms.ClearableFileInput(attrs={"class": "form-control"}),
            "doctor_name": forms.TextInput(attrs={"class": "form-control"}),
            "doctor_title": forms.TextInput(attrs={"class": "form-control"}),
            "doctor_bio": forms.Textarea(attrs={"class": "form-control", "rows": 4}),
        }
