from django.contrib.auth import views as auth_views
from django.urls import path

from .views import (
    RememberMeLoginView,
    appointments,
    appointments_chart,
    appointments_form,
    blog_post_bulk_action,
    blog_post_create,
    blog_post_delete,
    blog_post_edit,
    blog_post_toggle_publish,
    blog_posts,
    inquiries,
    index,
    message,
    patients,
    profile,
    settings_page,
    testimonial_bulk_action,
    testimonial_create,
    testimonial_delete,
    testimonial_edit,
    testimonial_toggle_publish,
    testimonials,
    website,
)

app_name = "dashboard"

urlpatterns = [
    path("", index, name="home"),
    path("appointments/", appointments, name="appointments"),
    path("appointments/new/", appointments_form, name="appointments_form"),
    path("patients/", patients, name="patients"),
    path("inquiries/", inquiries, name="inquiries"),
    path("message/", message, name="message"),
    path("website/", website, name="website"),
    path("testimonials/", testimonials, name="testimonials"),
    path("testimonials/new/", testimonial_create, name="testimonial_create"),
    path("testimonials/<int:pk>/edit/", testimonial_edit, name="testimonial_edit"),
    path("testimonials/bulk/", testimonial_bulk_action, name="testimonial_bulk"),
    path("testimonials/<int:pk>/toggle/", testimonial_toggle_publish, name="testimonial_toggle"),
    path("testimonials/<int:pk>/delete/", testimonial_delete, name="testimonial_delete"),
    path("profile/", profile, name="profile"),
    path("blog/", blog_posts, name="blog"),
    path("blog/new/", blog_post_create, name="blog_create"),
    path("blog/<int:pk>/edit/", blog_post_edit, name="blog_edit"),
    path("blog/bulk/", blog_post_bulk_action, name="blog_bulk"),
    path("blog/<int:pk>/toggle/", blog_post_toggle_publish, name="blog_toggle"),
    path("blog/<int:pk>/delete/", blog_post_delete, name="blog_delete"),
    path("settings/", settings_page, name="settings"),
    path("login/", RememberMeLoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("chart-date/", appointments_chart, name="appointments_chart"),
]
