# Generated by Django 6.0 on 2026-03-22 17:45

import apps.patients.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_move_patient_from_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('document_type', models.CharField(choices=[('insurance', 'Insurance Image'), ('agreement', 'Agreement Document'), ('consent', 'Consent Form'), ('id_copy', 'ID Copy'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to=apps.patients.models.patient_document_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
